config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :results, only: [:index]
  
  resources :labels, only: [:show, :new, :create, :edit, :update] do
    get '/follow', to: 'labels#follow'
    get '/unfollow', to: 'labels#unfollow'
    resources :events, only: [:new, :create]
  end

  resources :artists do
    get '/follow', to: 'artists#follow'
    get '/unfollow', to: 'artists#unfollow'
    resources :songs, only: [:new, :create]
    resources :events, only: [:new, :create]
  end

  resources :chatrooms, only: [:show, :create, :index] do
    resources :messages, only: [:create]
  end

  resources :connections, only: [:index, :create, :destroy]

  
  get '/styleguide', to: 'pages#styleguide'
  get '/redirect', to: 'pages#redirect'
  get '/spotify', to: 'pages#spotify'

end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :user1, foreign_key: :user1_id, class_name: "User"
  belongs_to :user2, foreign_key: :user2_id, class_name: "User"

  validates :user1_id, presence: true
  validates :user2_id, presence: true

  def connection_suggestion
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @connectons = Connection.all
  end

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    redirect_back fallback_location: root_path
  end

  def destroy
    @connection = Connection.find(params[:id])
    @connection.destroy
    redirect_back fallback_location: root_path
  end
end

app/views/connections/index.html.erb
<div class="container container-suggestions text-center pt-3">
  <h2 class="pt-3 text-center"> Start your journey </h2>
  <h2 class="pt-3 mb-5 text-center"> connecting with </h2>
  <%# <%= Artist.all.name%>
  <div class="row row-suggestions m-3">
    <% unless current_user == @user %>
      <% @profiles = Artist.all.first(3) + Label.all.first(3)  %>
      <% @profiles.each do |profile| %>
        <%# based on location?  %>
        <div class="card-suggestion mt-3">
          <% if current_user.following?(profile.user) %>
            <div class="connect-card-items m-3">
              <div class="connect-card-infos">
                <div class="card-suggestion-avatar pl-3 mr-5">
                  <% if profile.photo.attached? %>
                    <%= cl_image_tag profile.photo.key, alt:"avatar profile", class: "avatar-large rounded-circle avatar-suggestion"%>
                  <% else %>
                    <%= image_tag "https://miro.medium.com/max/200/1*W35QUSvGpcLuxPo3SRTH4w.png", class: "avatar-large rounded-circle avatar-suggestion"%>
                  <% end %>
                </div>
                <div class="info-suggestions mt-3">
                  <h5><%= profile.name %></h5>
                  <p><%= profile.location %></p>
                </div>
              </div>
              <div>
                <%= link_to "Remove", connection_path(current_user.following_connection(profile.user)), method: :delete, class: "btn btn-blue px-5 mt-5" %>  <%# connect switch to connected %>
              </div>
            </div>
          <% else %>
            <div class="connect-card-items m-3">
              <div class="connect-card-infos">
                <div class="card-suggestion-avatar pl-3 mr-5">
                  <% if profile.photo.attached? %>
                    <%= cl_image_tag profile.photo.key, alt:"avatar profile", class: "avatar-large rounded-circle avatar-suggestion"%>
                  <% else %>
                    <%= image_tag "https://miro.medium.com/max/200/1*W35QUSvGpcLuxPo3SRTH4w.png", class: "avatar-large rounded-circle avatar-suggestion"%>
                  <% end %>
                </div>
                <div class="info-suggestions mt-3">
                  <h5><%= profile.name %></h5>
                  <p><%= profile.location %></p>
                </div>
              </div>
              <div>
                <%= link_to "Connect", connections_path({user_id: profile.user.id}), method: :post, class: "btn btn-gradient px-5 mt-5" %>  <%# connect switch to connected %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="container my-5">
    <% if current_user.label?  %>
      <%= link_to "Skip to Profile", label_path(current_user.profile_instance), class: "btn btn-blue py-2" %> <%# skip to profile page%>
    <% else %>
      <%= link_to "Skip to Profile", artist_path(current_user.profile_instance), class: "btn btn-blue py-2" %>
    <% end %>
  </div>
</div>
<%= render 'shared/footer' %>