config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :results, only: [:index]
  
  resources :labels, only: [:show, :new, :create, :edit, :update] do
    get '/follow', to: 'labels#follow'
    get '/unfollow', to: 'labels#unfollow'
    resources :events, only: [:new, :create]
  end

  resources :artists do
    get '/follow', to: 'artists#follow'
    get '/unfollow', to: 'artists#unfollow'
    resources :songs, only: [:new, :create]
    resources :events, only: [:new, :create]
  end

  resources :chatrooms, only: [:show, :create, :index] do
    resources :messages, only: [:create]
  end

  resources :connections, only: [:index, :create, :destroy]

  
  get '/styleguide', to: 'pages#styleguide'
  get '/redirect', to: 'pages#redirect'
  get '/spotify', to: 'pages#spotify'

end

app/models/artist.rb
class Artist < ApplicationRecord
  GENRES = %w[Jazz Rock Indie Pop Blues Punk Funk Reggae Soul Rap Metal Electronic Classical Folk]
  ROLES = %w[Singer Guitarist Drummer Bassist Keyboardist Composer Remixer Songwriter Producer DJ]

  INFLUENCES = [
    {
      name: 'Florence + The Machine', image: 'https://dynamicmedia.livenationinternational.com/Media/k/t/n/9cc3e38c-66b0-4160-8859-0feb42352add.jpg'
    },
    {
      name: 'Phoebe Bridgers', image: 'https://media.resources.festicket.com/www/artists/phoebe-bridgers-cover-story-interview.jpg'
    },
    {
      name: 'Erykah Badu', image: 'https://www.clubbingspain.com/imagenes/Erykah-Badu-2015-1200.jpg'
    },
    {
      name: 'Rage Against The Machine', image: 'https://www.rollingstone.com/wp-content/uploads/2020/02/Rage.jpg?resize=1800,1200&w=1800'
    },
    {
      name: 'Paramore', image: 'https://indiehoy.com/wp-content/uploads/2018/09/paramore.jpg'
    },
    {
      name: 'Cranberries', image: 'https://loff.it/wp-content/uploads/2018/01/loffit-muere-dolores-oriordan-cantante-de-the-cranberries-02.jpg'
    },
    {
      name: 'PJ Harvey', image: 'https://img.discogs.com/TTbGEo9x9D31sKJSeYi6_GcscU0=/600x600/smart/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/A-36052-1606316026-8044.jpeg.jpg'
    },
    {
      name: 'Patti Smith', image: 'https://note-store.es/upload/resize_cache/iblock/4ba/325_380_2/Patti-Smith.png'
    },
    {
      name: 'Fleetwood Mac', image: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Fleetwood_Mac_Billboard_1977.jpg'
    },
    {
      name: 'Radiohead', image: 'https://mixfm.mx/wp-content/uploads/2018/07/creep-radiohead-video.jpg'
    }
  ]

  belongs_to :user
  belongs_to :label, optional: true
  has_many :events, as: :organizable, dependent: :destroy
  has_many :songs, dependent: :destroy
  has_one_attached :photo
  validates :user, uniqueness: true
  validates :name, presence: true

  validate :valid_genre_list
  validate :valid_role_list

  before_create :pull_spotify_image
  before_update :pull_spotify_image, :if => Proc.new { |model| model.influences_changed? }
  after_create :set_user_type

  # scope :filter_by_genre, ->(search_genre) { where("'#{search_genre}' = Any(genres)") }
  scope :filter_by_genres, ->(search_genres) { where("genres @> ARRAY[?]::varchar[]", search_genres) } # it will match only if all slected genres are present
  # scope :filter_by_role, ->(search_role) { where("'#{search_role}' = Any(roles)") }
  scope :filter_by_roles, ->(search_roles) { where("roles @> ARRAY[?]::varchar[]", search_roles) }
  scope :filter_by_location, ->(search_location) { where location: search_location }


  def influences_list
    INFLUENCES.map { |influence| influence[:name] }
  end

  def influence_image(influence)
    JSON.parse(influence)['image']
  end

  def influences_name_list
    influences.map { |influence| JSON.parse(influence)['name'] }
  end


  def set_user_type
    user.artist!
  end


  private

  def pull_spotify_image
    self.influences = influences.map do |influence|
      artists = RSpotify::Artist.search(influence)
      image = artists.first.images.first['url']

      {'name' => influence, 'image' => image}.to_json
    end
  end

  def valid_genre_list
    diff = genres - GENRES
    diff.empty?
  end

  def valid_role_list
    diff = roles - ROLES
    diff.empty?
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[show edit update]
  before_action :following_users, only: %i[follow unfollow]
  before_action :redirect_if_profile_exists, only: %i[new]

  def show
    @song = Song.new
    if current_user.artist && current_user.artist.songs
      @songs = current_user.artist.songs
    else
      @songs = []
    end

    @event = Event.new
    @events = @artist.events.map do |event|
      {
        year: event.date.year,
        month: event.date.month,
        day: event.date.day,
        Date: [event.date.year, event.date.month, event.date.day],
        Title: event.name,
        Link: event.event_url,
        html: render_to_string(partial: "events/event_card", locals: { event: event })
      }
    end

    @grouped_events = {}
    @events.each do |event|
      @grouped_events[event[:year]] = @grouped_events[event[:year]] || {}
      @grouped_events[event[:year]][event[:month]] = @grouped_events[event[:year]][event[:month]] || {}
      @grouped_events[event[:year]][event[:month]][event[:day]] =
        @grouped_events[event[:year]][event[:month]][event[:day]] || []
      @grouped_events[event[:year]][event[:month]][event[:day]].push(event)
    end
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    @artist.user = current_user
    # authorize @artist
    if @artist.save!
      redirect_to connections_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to artist_path(@artist)
    else
      render :show
    end
  end

  def follow
    current_user.follow(@follow_user)
    redirect_to artist_path(@id_artist)
  end

  def unfollow
    current_user.unfollow(@follow_user)
    redirect_to artist_path(@id_artist)
  end

  private

  def artist_params
    params[:artist][:influences] = params[:artist][:influences]&.split(',')
    params.require(:artist).permit(:name, :age, :location, :bio, :photo, :soundcloud_url, :website_url, :youtube_url,
                                   :instagram_url, :user_type, genres: [], roles: [], influences: [])
  end

  def redirect_if_profile_exists
    redirect_to artist_path(current_user.artist) unless current_user.artist.nil?
  end

  def set_artist
    @artist = Artist.find(params[:id])
    # authorize @artist
  end

  def following_users
    @id_artist = params[:artist_id]
    @user = Artist.find(@id_artist).user_id
    @follow_user = User.find(@user)
  end
end

app/views/artists/_form.html.erb
<%= simple_form_for artist do |f| %>
  <%= render "artists/form_fields", f: f %>
  <div class="container text-center">
    <%= f.submit "Next: Connections", class: 'btb btn-gradient py-2' %>
  </div>
<% end %>

app/views/artists/_form_fields.html.erb
<div data-controller="spotify">
  <%= f.input :name, label:"What's your superstar name?" %>
  <%= f.input :age, label:'How many circles around the sun?' %>
  <%= f.input :location, label:'Where does your story begin?' %>
  <%= f.input :roles, collection: Artist::ROLES, label:'What are your superpowers?', include_hidden: false, input_html: { multiple: true } %>
  <%= f.input :bio, label:'What would your friends say about you as an artist?' %>
  <%= f.input :influences, as: :hidden, input_html: {data: {"spotify-target": "hidden", influences: @artist.influences_name_list }, value: @artist.influences_name_list.join(',') } %>
  <div class="d-flex flex-column form-group">
    <label class="string optional" for="artist_influences">Influences</label>
    <input type="text" id="autoComplete" data-spotify-target="input" class="form-control w-100">
    <div class="d-flex mt-2" data-spotify-target="container">
      <% @artist.influences_name_list.each do |influence| %>
        <span class="badge badge-primary mr-2"><%= influence %></span>
      <% end %>
    </div>
  </div>
  <%= f.input :genres, label:"What's your jam?", collection: Artist::GENRES, include_hidden: false, input_html: { multiple: true } %>
  <%= f.input :youtube_url, label:'Drop your proudest YouTube video url in here' %>
  <%= f.input :instagram_url, label: 'How about your Instagram? Add the url below'%>
  <%= f.input :photo, label:'Finally, time to upload your best photo', as: :file  %>
</div>

app/views/artists/new.html.erb
<div class="main d-flex">
  <div class="d-block full-width">
    <%= render "shared/simpletop" %>
  </div>
  <div class="container col-6 col-lg-4 my-5">
    <h1 class='text-center' data-spotify-target="title">Create your profile</h1>
    <%= render "artists/form", artist: @artist %>
  </div>
  <div class="d-block full-width">
    <%= render "shared/footer" %>
  </div>
</div>

      <%#= f.input :influences, collection: Artist::INFLUENCES.map {|influence| influence[:name]}, include_hidden: false, input_html: { multiple: true, max: 4 } %>

app/views/artists/show.html.erb
<!-- Navbar -->
<%= render 'shared/navbar' %>
<!-- Basic info card -->
<div class="container basic-info d-flex justify-content-between" data-controller="tabs">
  <div class="profile-card position-relative px-5">
    <% if @artist.photo.attached? %>
      <%= cl_image_tag @artist.photo.key, alt:"avatar profile", class:"avatar-profile", height:"200", width:"200" %>
    <% else %>
      <%= image_tag "https://miro.medium.com/max/200/1*W35QUSvGpcLuxPo3SRTH4w.png", class:"avatar-profile", height: "200", width:"200"%>
    <% end %>
    <% if current_user == @artist.user %>
      <%= link_to "javascript:;" do %>
        <i class="far fa-edit fa-2x edit-btn" data-toggle="modal" data-target="#infoModal"></i>
      <% end %>
    <% end %>
    <div class="text-center pb-3">
      <h2><%= @artist.name %> <%= @artist.age.nil? ? "" : "(#{@artist.age})" %></h2>
      <h4><%= @artist.location %></h4>
    </div>
    <div class="d-flex justify-content-around pb-2">
      <p>
        <% @artist.roles.each do |role| %>
          <span class="badge badge-pill badge-info p-2"><%= role %></span>
        <% end %>
      </p>
      <p>
        <% @artist.genres.each do |genre| %>
          <span class="badge badge-pill badge-light p-2">#<%= genre %></span>
        <% end %>
      </p>
    </div>
    <div class="d-flex justify-content-around">
      <% unless current_user == @artist.user %>
        <%= link_to "Message", chatrooms_path(profile_id: @artist.id, user_type: :artist), method: :post, class: "btn btn-gradient px-5" %>
        <% if current_user.following?(@artist.user) %>
          <%= link_to "Connected", artist_unfollow_path(@artist), class: "btn btn-blue px-5" %>
        <% else %>
          <%= link_to "Connect", artist_follow_path(@artist), class: "btn btn-gradient px-5" %>
        <% end %>
      <% end %>
    </div>
    <div class="info-text-profile">
      <h4 class="pt-3">About me</h4>
      <p><%= @artist.bio %></p>
      <h4 class="pt-3">My influences</h4>
    </div>
    <div class= "d-flex justify-content-around">
      <% @artist.influences.each do |influence| %>
        <%= image_tag @artist.influence_image(influence), class:"influences-avatar mt-4", data: { toggle: 'tooltip', placement: 'top', title: 'Facebook' } %>
      <% end %>
    </div>
  </div>
  <!-- links card -->
  <div class="profile-card-links py-5 my-5 position-relative">
    <%# TAB NAVIGATION %>
    <ul class="nav nav-tabs nav-profile" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link active nav-link-artist" id="links-tab" data-toggle="tab" href="#links" role="tab" aria-controls="links" aria-selected="true">My links</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link nav-link-artist" id="songs-tab" data-toggle="tab" href="#songs" role="tab" aria-controls="songs" aria-selected="false">My songs</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link nav-link-artist" id="events-tab" data-toggle="tab" href="#events" role="tab" aria-controls="events" aria-selected="false">Events</a>
      </li>
    </ul>
    <div class="tab-content">
      <%# LINKS TAB %>
      <div class="tab-pane fade show active" id="links" role="tabpanel" aria-labelledby="links-tab">
        <div class="p-4">
          <div class="position-relative">
            <% if current_user == @artist.user %>
              <%= link_to "javascript:;" do %>
                <i class="far fa-edit add-btn-links" data-toggle="modal" data-target="#linksModal"></i>
              <% end %>
            <% end %>
          </div>
          <h4 class="mb-4">YouTube</h4>
          <div class="container d-flex justify-content-around">
            <iframe width="370" height="200" src="<%= @artist.youtube_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="container d-block">
            <h4 class="insta-h p-2 mt-5">Instagram</h4>
            <div class="container d-flex justify-content-around">
              <blockquote class="instagram-media" data-instgrm-version="7" >
                <a href="<%= @artist.instagram_url %>"></a>
              </blockquote>
              <script async defer src="//platform.instagram.com/en_US/embeds.js"></script>
            </div>
          </div>
        </div>
      </div>
      <%# SONGS TAB %>
      <div class="tab-pane fade" id="songs" role="tabpanel" aria-labelledby="songs-tab" data-controller='flipcard'>
        <div class="p-4">
        <div class="position-relative">
          <% if current_user == @artist.user %>
            <%= link_to "javascript:;" do %>
              <i class="far fa-plus-square fa-2x add-btn-links" data-toggle="modal" data-target="#songsModal"></i>
            <% end %>
          <% end %>
        </div>
          <h4 class="mb-5">My latests releases</h4>
          <% @songs.each do |song| %>
            <div class="flip-card-wrapper mb-3">
              <div id="flip-card" class='flipable-card' data-action='click->flipcard#flip'>
                <div class="card__face card__face--front">
                  <div class="flip-card-info">
                    <h5><%= song.title %></h5>
                    <p>released on <%= song.released %></p>
                  </div>
                  <% if song.track.attached? %>
                    <div class="pl-2">
                      <audio controls>
                        <source src="<%= cl_video_path song.track.key %>" type="audio/mpeg">
                        Your browser does not support the audio tag.
                      </audio>
                    </div>
                  <% end %>
                </div>
                <div class='card__face card__face--back'>
                  <p class="song-description"><%= song.song_description %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <%# EVENTS TAB %>
      <div class="tab-pane fade" id="events" role="tabpanel" aria-labelledby="events-tab">
        <div class="p-4">
          <div class="position-relative">
            <% if current_user == @artist.user %>
              <%= link_to "javascript:;" do %>
                <i class="far fa-edit add-btn-links" data-toggle="modal" data-target="#eventsModal"></i>
              <% end %>
            <% end %>
          </div>
          <h4 class="cal-h mb-5">My calendar</h4>
            <div class="container d-block">
              <div class="d-flex flex-column">
                <div class="d-flex justify-content-center">
                  <%= render 'shared/calendar' %>
                </div>
                <div class="d-flex justify-content-center">
                  <div id="artist-events"></div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Info Modal -->
<div class="modal fade" id="infoModal" tabindex="-1" aria-labelledby="infoModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="infoModalLabel">Edit your details</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @artist do |f| %>
          <%= render "artists/form_fields", f: f %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Update", class: 'btn btn-blue p-2' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Links Modal -->
<div class="modal fade" id="linksModal" tabindex="-1" aria-labelledby="linksModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="linksModalLabel">Edit your links</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @artist do |f| %>
          <%= f.input :youtube_url %>
          <%= f.input :instagram_url %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Update", class: 'btn btn-blue p-2' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Songs Modal -->
<div class="modal fade" id="songsModal" tabindex="-1" aria-labelledby="songsModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="songsModalLabel">Upload your songs</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@artist, @song] do |f| %>
          <%= f.input :title %>
          <%= f.input :released %>
          <%= f.input :song_description %>
          <%= f.input :track, as: :file%>
        </div>
        <div class="modal-footer">
          <%= f.submit "Upload", class: 'btn btn-blue p-2' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- Events Modal -->
<div class="modal fade" id="eventsModal" tabindex="-1" aria-labelledby="eventsModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="eventsModalLabel">Create an Event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: "events/new", locals: {organizable: @artist} %>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>