config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :results, only: [:index]
  
  resources :labels, only: [:show, :new, :create, :edit, :update] do
    get '/follow', to: 'labels#follow'
    get '/unfollow', to: 'labels#unfollow'
    resources :events, only: [:new, :create]
  end

  resources :artists do
    get '/follow', to: 'artists#follow'
    get '/unfollow', to: 'artists#unfollow'
    resources :songs, only: [:new, :create]
    resources :events, only: [:new, :create]
  end

  resources :chatrooms, only: [:show, :create, :index] do
    resources :messages, only: [:create]
  end

  resources :connections, only: [:index, :create, :destroy]

  
  get '/styleguide', to: 'pages#styleguide'
  get '/redirect', to: 'pages#redirect'
  get '/spotify', to: 'pages#spotify'

end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
  has_many :events, as: :organizable
  has_many :artists, dependent: :destroy
  has_one_attached :photo
  scope :filter_by_location, -> { where location: location }

  after_create :set_user_type

  validates :user, uniqueness: true
  validates :name, presence: true

  def set_user_type
    user.label!
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_label, only: %i[show edit update]
  before_action :following_users, only: %i[follow unfollow]
  before_action :redirect_if_profile_exists, only: %i[new]

  def new
    @label = Label.new
  end

  def create
    @label = Label.new(label_params)

    @label.user = current_user
    # authorize @label

    if @label.save!
      redirect_to connections_path
    else
      render :new
    end
  end

  def show
    @event = Event.new
    @events = @label.events.map do |event|
      {
        year: event.date.year,
        month: event.date.month,
        day: event.date.day,
        Date: [event.date.year, event.date.month, event.date.day],
        Title: event.name,
        Link: event.event_url,
        html: render_to_string(partial: "events/event_card", locals: { event: event })
      }
    end

    @grouped_events = {}
    @events.each do |event|
      @grouped_events[event[:year]] = @grouped_events[event[:year]] || {}
      @grouped_events[event[:year]][event[:month]] = @grouped_events[event[:year]][event[:month]] || {}
      @grouped_events[event[:year]][event[:month]][event[:day]] =
        @grouped_events[event[:year]][event[:month]][event[:day]] || []
      @grouped_events[event[:year]][event[:month]][event[:day]].push(event)
    end
  end

  def edit
  end

  def update
    if @label.update(label_params)
      redirect_to label_path(@label)
    else
      render :show
    end
  end

  def follow
    current_user.follow(@follow_user)
    redirect_to label_path(@id_label)
  end

  def unfollow
    current_user.unfollow(@follow_user)
    redirect_to label_path(@id_label)
  end

  private

  def label_params
    params.require(:label).permit(:name, :location, :bio, :photo, :website_url, :user_type)
  end

  def redirect_if_profile_exists
    redirect_to label_path(current_user.label) unless current_user.label.nil?
  end

  def set_label
    @label = Label.find(params[:id])
    # authorize @label
  end

  def following_users
    @id_label = params[:label_id]
    @user = Label.find(@id_label).user_id
    @follow_user = User.find(@user)
  end
end

app/views/labels/new.html.erb
<div class="main d-flex">
  <div class="d-block full-width">
    <%= render "shared/simpletop" %>
  </div>
  <div class="container col-6 col-lg-4 my-5">
    <h1 class="text-center">Create a profile</h1>
    <%= simple_form_for(@label) do |f| %>
      <%= f.input :name %>
      <%= f.input :location %>
      <%= f.input :bio %>
      <%= f.input :website_url %>
      <%= f.input :photo, as: :file  %>
      <div class="container text-center">
        <%= f.submit "Create", class: 'btb btn-gradient p-2 px-4' %>
      </div>
    <% end %>
  </div>
  <div class="d-block full-width">
    <%= render "shared/footer" %>
  </div>
</div>

app/views/labels/show.html.erb
<!-- Navbar -->
<%= render 'shared/navbar' %>
<!-- Basic info card -->
<div class="container basic-info d-flex justify-content-between" data-controller="tabs">
  <div class="profile-card position-relative px-5">
    <% if @label.photo.attached? %>
      <%= cl_image_tag @label.photo.key, alt:"avatar profile", class:"avatar-profile", height:"200", width:"200" %>
    <% else %>
      <%= image_tag "https://miro.medium.com/max/200/1*W35QUSvGpcLuxPo3SRTH4w.png", class:"avatar-profile", height: "200", width:"200"%>
    <% end %>
    <% if current_user == @label.user%>
      <%= link_to "javascript:;" do %>
        <i class="far fa-edit fa-2x edit-btn" data-toggle="modal" data-target="#exampleModalCenter"></i>
      <% end %>
    <% end %>
    <div class="text-center pb-3">
      <h2><%= @label.name %></h2>
      <h4><%= @label.location %></h4>
    </div>
    <div class="d-flex justify-content-around">
      <% unless current_user == @label.user %>
        <%= link_to "Message", chatrooms_path(profile_id: @label.id, user_type: :label), method: :post, class: "btn btn-gradient px-5" %>
        <% if current_user.following?(@label.user) %>
          <%= link_to "Connected", label_unfollow_path(@label), class: "btn btn-blue px-5" %>
        <% else %>
          <%= link_to "Connect", label_follow_path(@label), class: "btn btn-gradient px-5" %>
        <% end %>
      <% end %>
    </div>
    <div class="">
      <h4 class="pt-3">About us</h4>
      <p><%= @label.bio %></p>
    </div>
  </div>
  <div class="profile-card-links py-5 my-5">
    <%# TAB NAVIGATION %>
    <ul class="nav nav-tabs nav-profile" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link active nav-link-artist" id="artistlist-tab" data-toggle="tab" href="#artistlist" role="tab" aria-controls="artistlist" aria-selected="true">Our artists</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link nav-link-artist" id="labellinks-tab" data-toggle="tab" href="#labellinks" role="tab" aria-controls="labellinks" aria-selected="false">Our links</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link nav-link-artist" id="events-tab" data-toggle="tab" href="#events" role="tab" aria-controls="events" aria-selected="false">Events</a>
      </li>
    </ul>
    <div class="tab-content">
      <%# artistlist TAB %>
      <div class="tab-pane fade show active p-4" id="artistlist" role="tabpanel" aria-labelledby="artistlist-tab">
        <div class="position-relative">
          <% if current_user == @label.user %>
            <%= link_to "javascript:;" do %>
              <i class="far fa-edit edit-btn-links" data-toggle="modal" data-target="#artistlistModal"></i>
            <% end %>
          <% end %>
        </div>
        <h4>Our artists</h4>
      </div>
      <%# links TAB %>
      <div class="tab-pane fade p-4" id="labellinks" role="tabpanel" aria-labelledby="labellinks-tab">
        <div class="position-relative">
          <% if current_user == @label.user %>
            <%= link_to "javascript:;" do %>
              <i class="far fa-edit add-btn-links" data-toggle="modal" data-target="#labellinksModal"></i>
            <% end %>
          <% end %>
        </div>
        <h4>Official website</h4>
        <% unless @label.website_url.nil? %>
          <%= link_to "Visit our page", url_for("https://#{@label.website_url}"), target: "_blank", class:"btn btn-blue m-4"  %>
        <% end %>
      </div>
      <%# EVENTS TAB %>
      <div class="tab-pane fade p-4" id="events" role="tabpanel" aria-labelledby="events-tab">
        <div class="position-relative">
          <% if current_user == @label.user %>
            <%= link_to "javascript:;" do %>
              <i class="far fa-edit add-btn-links" data-toggle="modal" data-target="#eventsModal"></i>
            <% end %>
          <% end %>
        </div>
        <h4 class="cal-h mb-5">Our calendar</h4>
        <div class="d-flex justify-content-center mt-4">
          <%= render 'shared/calendar' %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<!-- Basic info Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Edit your information</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@label) do |f| %>
          <%= f.input :name %>
          <%= f.input :location %>
          <%= f.input :bio %>
          <%= f.input :website_url %>
          <%= f.input :photo, as: :file  %>
          <%= f.submit "Update", class: 'btn btn-blue p-2' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Artist list Modal -->
<div class="modal fade" id="artistlistModal" tabindex="-1" role="dialog" aria-labelledby="artistlistModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="artistlistModalTitle">Edit your information</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@label) do |f| %>
          <%= f.input :name %>
          <%= f.input :location %>
          <%= f.input :bio %>
          <%= f.input :website_url %>
          <%= f.submit "Update", class: 'btn btn-blue p-2' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Links Modal -->
<div class="modal fade" id="labellinksModal" tabindex="-1" role="dialog" aria-labelledby="labellinksModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="labellinksModalTitle">Edit your information</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@label) do |f| %>
          <%= f.input :website_url %>
          <%= f.submit "Update", class: 'btn btn-blue p-2' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Events Modal -->
<div class="modal fade" id="eventsModal" tabindex="-1" aria-labelledby="eventsModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="eventsModalLabel">Create an Event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: "events/new", locals: {organizable: @label} %>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>