config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :results, only: [:index]
  
  resources :labels, only: [:show, :new, :create, :edit, :update] do
    get '/follow', to: 'labels#follow'
    get '/unfollow', to: 'labels#unfollow'
    resources :events, only: [:new, :create]
  end

  resources :artists do
    get '/follow', to: 'artists#follow'
    get '/unfollow', to: 'artists#unfollow'
    resources :songs, only: [:new, :create]
    resources :events, only: [:new, :create]
  end

  resources :chatrooms, only: [:show, :create, :index] do
    resources :messages, only: [:create]
  end

  resources :connections, only: [:index, :create, :destroy]

  
  get '/styleguide', to: 'pages#styleguide'
  get '/redirect', to: 'pages#redirect'
  get '/spotify', to: 'pages#spotify'

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def index
    @artists = Artist.all
    @labels = Label.all
    if params[:filter].present?
      @query = params[:filter][:query]
      @search_genres = params[:filter][:genres]
      @search_roles = params[:filter][:roles]
      @search_location = params[:filter][:location]
      @artists = @artists.where('name ilike ?', "%#{@query}%") if @query
      @labels = Label.where('name ilike ?', "%#{@query}%") if @query
      @artists = @artists.filter_by_genres(@search_genres) if @search_genres
      @artists = @artists.filter_by_roles(@search_roles) if @search_roles
      @artists = @artists.filter_by_location(@search_location) if @search_location.present?
    end
  end
end

app/views/results/index.html.erb
<!-- Navbar -->
<div class="navbar navbar-expand-sm navbar-light navbar-main">
  <div class="d-flex">
    <%= link_to root_path, class: "navbar-brand ml-2" do %>
      <%= image_tag "logo.png", class:"rounded-circle", style: 'height:50px;width:auto;'%>
    <% end %>
    <h1 class="align-self-center pt-2">SpotLight</h1>
  </div>
  <%= simple_form_for(:filter, method: :get, url: results_path) do |f| %>
    <div class="search-form-control form-group">
      <%= f.input :query, required: false, class: "form-control string required", placeholder: "Search for artists and labels", label: false %>
      <%= submit_tag "Search", class: "btn-search btn-blue "%>
    </div>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item mr-5">
        <%= link_to results_path, class: "nav-link" do %>
          <i class="fas fa-search fa-lg"></i>
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <%= link_to chatrooms_path, class: "nav-link" do %>
          <i class="far fa-comment-alt fa-lg"></i>
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <%= link_to "#", class: "nav-link" do %>
          <i class="far fa-bell fa-lg"></i>
        <% end %>
      </li>
      <li class="nav-item dropdown mr-4">
        <% if current_user.profile_instance.photo.attached? %>
          <%= cl_image_tag current_user.profile_instance.photo.key, alt:"avatar profile", class: "avatar dropdown-toggle rounded-circle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false,  height:"40", width:"40"%>
        <% else %>
          <%= image_tag "https://miro.medium.com/max/200/1*W35QUSvGpcLuxPo3SRTH4w.png", class: "avatar dropdown-toggle rounded-circle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false,  height:"40", width:"40"%>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "My profile", current_user.profile_path , class: "dropdown-item mt-2" %>
          <%= link_to "Settings", "#" , class: "dropdown-item my-2" %>
          <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item logout-item" do %>
            <div class="d-flex align-self-center my-2 mx-3">
              <i class="fas fa-sign-out-alt logout-icon mr-2 align-self-center"></i>
              <p class="m-0">Log out</p>
            </div>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>
<!-- Search -->
<div class="container m-0 pl-0">
  <div class="d-flex justify-content-between">
    <div>

       <div class="filter-search my-5 p-3" data-controller="filters">
        <%= simple_form_for(:filter, method: :get, url: results_path, data: {"filters-target": "form"}) do |f| %>
        <%= f.input :query, as: :hidden, input_html: {value: @query} %>
        <%= f.input :genres, as: :check_boxes, collection: Artist::GENRES, required: false, include_hidden: false, input_html: { multiple: true, data: {action: "change->filters#filter", 'filters-target': 'checkbox'} } %>
        <%= f.input :roles, as: :check_boxes, collection: Artist::ROLES, required: false, include_hidden: false, input_html: { multiple: true, data: {action: "change->filters#filter", 'filters-target': 'checkbox'} } %>
        <%= f.input :location, required: false, placeholder: 'Type the location'%>
        <%= f.submit 'Submit', class: 'btb btn-gradient p-2 px-3' %> <%= link_to "Clear", results_path, class: "clear-link" %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-9 mt-5">
      <% if @artists.empty? %>
        <p class="text-center">Sorry, but there are no Artists that match your search.</p>
      <% else %>
        <div class="artist-search">
          <h2>Artists</h2>
          <% @artists.each do |artist| %>
            <%= link_to artist_path(artist) do%>
              <div class="card-search d-flex justify-content-between p-2">
                <div class="card-search-avatar pt-4 pr-5 pl-3">
                  <% if artist.photo.attached? %>
                    <%= cl_image_tag artist.photo.key, alt:"avatar profile", class: "avatar-large rounded-circle avatar-search"%>
                  <% else %>
                    <%= image_tag "https://miro.medium.com/max/200/1*W35QUSvGpcLuxPo3SRTH4w.png", class: "avatar-large rounded-circle avatar-search"%>
                  <% end %>
                </div>
                <div class="card-search-info">
                  <h5><%= artist.name %></h5>
                  <p><%= artist.location %></p>
                  <p>
                    <% artist.roles.each do |role| %>
                      <span class="badge badge-pill badge-info p-2"><%= role %></span>
                    <% end %>
                  </p>
                  <p>
                    <% artist.genres.each do |genre| %>
                      <span class="badge badge-pill badge-light p-2">#<%= genre %></span>
                    <% end %>
                  </p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <% if @labels.empty? %>
        <p class="text-center">Sorry, but there are no Labels that match your search.</p>
      <% else %>
        <div class="label-search">
          <h2>Labels</h2>
          <% @labels.each do |label| %>
            <%= link_to label_path(label) do%>
              <div class="card-search d-flex justify-content-between p-2">
                <div class="card-search-avatar pt-4 pr-5 pl-3">
                  <% if label.photo.attached? %>
                    <%= cl_image_tag label.photo.key, alt:"avatar profile", class: "avatar-large rounded-circle avatar-search"%>
                  <% else %>
                    <%= image_tag "https://miro.medium.com/max/200/1*W35QUSvGpcLuxPo3SRTH4w.png",class: "avatar-large rounded-circle avatar-search"%>
                  <% end %>
                </div>
                <div class="card-search-info pt-5">
                  <h5><%= label.name %></h5>
                  <p><%= label.location %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- Footer -->
<div class="d-block full-width">
  <%= render "shared/footer" %>
</div>